import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Proyecto 1 CPD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container">
          <div className="row">
            <div className="col-md-6">
              <form>
                <h2>Add a Book</h2>
                <div className="form-group">
                  <label htmlFor="bookId">Book ID</label>
                  <input type="text" className="form-control" id="bookId" name="bookId" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="title">Title</label>
                  <input type="text" className="form-control" id="title" name="title" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="authorFirstName">Author First Name</label>
                  <input type="text" className="form-control" id="authorFirstName" name="authorFirstName" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="authorLastName">Author Last Name</label>
                  <input type="text" className="form-control" id="authorLastName" name="authorLastName" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="rating">Rating</label>
                  <select className="form-control" id="rating" name="rating" required>
                    <option value="" selected disabled>Select a rating</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                  </select>
                </div>
                <button type="submit" className="btn btn-primary">Add Book</button>
              </form>
            </div>
            <div className="col-md-6">
              <form>
                <h2>Add Employee</h2>
                <div className="form-group">
                  <label htmlFor="employeeId">Employee ID</label>
                  <input type="text" className="form-control" id="employeeId" name="employeeId" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="firstName">First Name</label>
                  <input type="text" className="form-control" id="firstName" name="firstName" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="lastName">Last Name</label>
                  <input type="text" className="form-control" id="lastName" name="lastName" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="email">Email</label>
                  <input type="email" className="form-control" id="email" name="email" required/>
                </div>
                <div className="form-group">
                  <label htmlFor="phone">Phone</label>
                  <input type="text" className="form-control" id="phone" name="phone" required/>
                </div>
                <button type="submit" className="btn btn-primary">Add Employee</button>
              </form>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <h2>Books</h2>
              <table className="table">
                <thead>
                  <tr>
                    <th>Book_id</th>
                    <th>Title</th>
                    <th>Author_first_name</th>
                    <th>Author_last_name</th>
                    <th>Rating</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1</td>
                    <td>Harry Potter</td>
                    <td>J.K.</td>
                    <td>Rowling</td>
                    <td>5</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div className="col-md-6">
              <h2>Employees</h2>
              <table className="table">
                  <thead>
                    <tr>
                      <th>Employee_id</th>
                      <th>Name</th>
                      <th>Lastname</th>
                      <th>Email</th>
                      <th>Phone</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>1</td>
                      <td>Mohamed</td>
                      <td>Pérez</td>
                      <td>MPerez@yopmail.com</td>
                      <td>1234567891</td>
                    </tr>
                  </tbody>
                </table>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
